spring:
  r2dbc.initialization-mode: always
  data.mongodb.auto-index-creation: true

de:
  flapdoodle:
    mongodb.embedded.version: 4.0.2

logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
    io.r2dbc: DEBUG